// Calculated with this script: https://gist.github.com/Baccega/ff654a8f0ee1365f9e4cbd382f3a8489
export const COMUNI_VENETO_WITH_DISTANCES_FROM_SHOP = [
  { name: "Abano Terme", distance: 29.06 },
  { name: "Adria", distance: 64.51 },
  { name: "Affi", distance: 83.44 },
  { name: "Agna", distance: 50.71 },
  { name: "Agordo", distance: 75.2 },
  { name: "Agugliaro", distance: 38.37 },
  { name: "Alano di Piave", distance: 32.51 },
  { name: "Albaredo d'Adige", distance: 55.72 },
  { name: "Albettone", distance: 35.57 },
  { name: "Albignasego", distance: 30.1 },
  { name: "Alleghe", distance: 88.77 },
  { name: "Alonte", distance: 43.0 },
  { name: "Altavilla Vicentina", distance: 32.34 },
  { name: "Altissimo", distance: 46.21 },
  { name: "Altivole", distance: 17.39 },
  { name: "Angiari", distance: 62.39 },
  { name: "Anguillara Veneta", distance: 53.4 },
  { name: "Annone Veneto", distance: 67.84 },
  { name: "Arcade", distance: 34.53 },
  { name: "Arcole", distance: 52.49 },
  { name: "Arcugnano", distance: 26.79 },
  { name: "Ariano nel Polesine", distance: 77.82 },
  { name: "Arquà Petrarca", distance: 40.08 },
  { name: "Arquà Polesine", distance: 68.07 },
  { name: "Arre", distance: 44.86 },
  { name: "Arsiè", distance: 41.17 },
  { name: "Arsiero", distance: 43.36 },
  { name: "Arzergrande", distance: 41.59 },
  { name: "Arzignano", distance: 41.0 },
  { name: "Asiago", distance: 38.82 },
  { name: "Asigliano Veneto", distance: 46.71 },
  { name: "Asolo", distance: 20.07 },
  { name: "Auronzo di Cadore", distance: 113.43 },
  { name: "Badia Calavena", distance: 54.22 },
  { name: "Badia Polesine", distance: 64.37 },
  { name: "Bagnoli di Sopra", distance: 47.93 },
  { name: "Bagnolo di Po", distance: 72.2 },
  { name: "Baone", distance: 43.39 },
  { name: "Barbarano Vicentino", distance: 33.25 },
  { name: "Barbona", distance: 58.4 },
  { name: "Bardolino", distance: 87.97 },
  { name: "Bassano del Grappa", distance: 18.63 },
  { name: "Battaglia Terme", distance: 37.0 },
  { name: "Belfiore", distance: 56.07 },
  { name: "Belluno", distance: 64.67 },
  { name: "Bergantino", distance: 77.38 },
  { name: "Bevilacqua", distance: 55.61 },
  { name: "Boara Pisani", distance: 57.15 },
  { name: "Bolzano Vicentino", distance: 17.49 },
  { name: "Bonavigo", distance: 59.47 },
  { name: "Borca di Cadore", distance: 95.49 },
  { name: "Borgoricco", distance: 11.8 },
  { name: "Borso del Grappa", distance: 22.81 },
  { name: "Bosaro", distance: 69.11 },
  { name: "Boschi Sant'Anna", distance: 58.63 },
  { name: "Bosco Chiesanuova", distance: 63.12 },
  { name: "Bovolenta", distance: 39.19 },
  { name: "Bovolone", distance: 69.45 },
  { name: "Breda di Piave", distance: 39.64 },
  { name: "Breganze", distance: 24.06 },
  { name: "Brendola", distance: 35.19 },
  { name: "Brentino Belluno", distance: 74.19 },
  { name: "Brenzone", distance: 84.82 },
  { name: "Bressanvido", distance: 16.98 },
  { name: "Brogliano", distance: 37.47 },
  { name: "Brugine", distance: 37.58 },
  { name: "Bussolengo", distance: 79.53 },
  { name: "Buttapietra", distance: 72.6 },
  { name: "Cadoneghe", distance: 19.58 },
  { name: "Caerano di San Marco", distance: 22.27 },
  { name: "Calalzo di Cadore", distance: 101.01 },
  { name: "Caldiero", distance: 56.77 },
  { name: "Caldogno", distance: 26.69 },
  { name: "Calto", distance: 79.47 },
  { name: "Caltrano", distance: 35.14 },
  { name: "Calvene", distance: 30.71 },
  { name: "Camisano Vicentino", distance: 15.53 },
  { name: "Campagna Lupia", distance: 35.11 },
  { name: "Campiglia dei Berici", distance: 39.36 },
  { name: "Campo San Martino", distance: 8.58 },
  { name: "Campodarsego", distance: 13.75 },
  { name: "Campodoro", distance: 15.94 },
  { name: "Campolongo Maggiore", distance: 36.36 },
  { name: "Campolongo sul Brenta", distance: 25.86 },
  { name: "Camponogara", distance: 31.53 },
  { name: "Camposampiero", distance: 8.87 },
  { name: "Canale d'Agordo", distance: 82.26 },
  { name: "Canaro", distance: 77.06 },
  { name: "Canda", distance: 70.24 },
  { name: "Candiana", distance: 45.51 },
  { name: "Caorle", distance: 79.7 },
  { name: "Cappella Maggiore", distance: 55.43 },
  { name: "Caprino Veronese", distance: 81.72 },
  { name: "Carbonera", distance: 34.87 },
  { name: "Carceri", distance: 50.11 },
  { name: "Carmignano di Brenta", distance: 10.95 },
  { name: "Carrè", distance: 33.47 },
  { name: "Cartigliano", distance: 15.75 },
  { name: "Cartura", distance: 38.86 },
  { name: "Casale di Scodosia", distance: 56.32 },
  { name: "Casale sul Sile", distance: 37.22 },
  { name: "Casaleone", distance: 71.02 },
  { name: "Casalserugo", distance: 33.95 },
  { name: "Casier", distance: 35.02 },
  { name: "Cassola", distance: 13.26 },
  { name: "Castagnaro", distance: 65.03 },
  { name: "Castegnero", distance: 27.78 },
  { name: "Castel d'Azzano", distance: 75.44 },
  { name: "Castelbaldo", distance: 62.85 },
  { name: "Castelcucco", distance: 23.87 },
  { name: "Castelfranco Veneto", distance: 8.5 },
  { name: "Castelgomberto", distance: 35.2 },
  { name: "Castelguglielmo", distance: 70.22 },
  { name: "Castellavazzo", distance: 82.32 },
  { name: "Castello di Godego", distance: 8.75 },
  { name: "Castelmassa", distance: 78.56 },
  { name: "Castelnovo Bariano", distance: 78.96 },
  { name: "Castelnuovo del Garda", distance: 86.66 },
  { name: "Cavaion Veronese", distance: 84.32 },
  { name: "Cavallino-Treporti", distance: 54.76 },
  { name: "Cavarzere", distance: 56.86 },
  { name: "Cavaso del Tomba", distance: 27.33 },
  { name: "Cazzano di Tramigna", distance: 52.64 },
  { name: "Ceggia", distance: 62.05 },
  { name: "Cencenighe Agordino", distance: 81.25 },
  { name: "Ceneselli", distance: 76.78 },
  { name: "Cerea", distance: 68.52 },
  { name: "Ceregnano", distance: 63.39 },
  { name: "Cerro Veronese", distance: 62.75 },
  { name: "Cervarese Santa Croce", distance: 24.94 },
  { name: "Cesiomaggiore", distance: 53.42 },
  { name: "Cessalto", distance: 60.67 },
  { name: "Chiampo", distance: 44.78 },
  { name: "Chiarano", distance: 58.58 },
  { name: "Chies d'Alpago", distance: 74.59 },
  { name: "Chioggia", distance: 55.96 },
  { name: "Chiuppano", distance: 33.96 },
  { name: "Cibiana di Cadore", distance: 92.11 },
  { name: "Cimadolmo", distance: 44.2 },
  { name: "Cinto Caomaggiore", distance: 76.42 },
  { name: "Cinto Euganeo", distance: 40.75 },
  { name: "Cismon del Grappa", distance: 34.76 },
  { name: "Cison di Valmarino", distance: 45.11 },
  { name: "Cittadella", distance: 5.94 },
  { name: "Codevigo", distance: 43.74 },
  { name: "Codognè", distance: 53.25 },
  { name: "Cogollo del Cengio", distance: 37.39 },
  { name: "Colle Santa Lucia", distance: 93.29 },
  { name: "Colle Umberto", distance: 52.33 },
  { name: "Cologna Veneta", distance: 49.63 },
  { name: "Colognola ai Colli", distance: 55.44 },
  { name: "Comelico Superiore", distance: 119.74 },
  { name: "Cona", distance: 49.99 },
  { name: "Concamarise", distance: 71.75 },
  { name: "Conco", distance: 27.46 },
  { name: "Concordia Sagittaria", distance: 78.99 },
  { name: "Conegliano", distance: 46.49 },
  { name: "Conselve", distance: 43.07 },
  { name: "Corbola", distance: 70.7 },
  { name: "Cordignano", distance: 57.62 },
  { name: "Cornedo Vicentino", distance: 39.28 },
  { name: "Cornuda", distance: 26.79 },
  { name: "Correzzola", distance: 45.92 },
  { name: "Cortina d'Ampezzo", distance: 104.6 },
  { name: "Costa di Rovigo", distance: 64.34 },
  { name: "Costabissara", distance: 28.15 },
  { name: "Costermano", distance: 86.22 },
  { name: "Creazzo", distance: 30.05 },
  { name: "Crespadoro", distance: 48.26 },
  { name: "Crespano del Grappa", distance: 23.11 },
  { name: "Crespino", distance: 70.83 },
  { name: "Crocetta del Montello", distance: 27.27 },
  { name: "Curtarolo", distance: 10.72 },
  { name: "Danta di Cadore", distance: 117.56 },
  { name: "Dolcè", distance: 77.28 },
  { name: "Dolo", distance: 27.8 },
  { name: "Domegge di Cadore", distance: 103.34 },
  { name: "Due Carrare", distance: 36.22 },
  { name: "Dueville", distance: 23.21 },
  { name: "Enego", distance: 37.61 },
  { name: "Eraclea", distance: 64.83 },
  { name: "Erbè", distance: 80.17 },
  { name: "Erbezzo", distance: 65.76 },
  { name: "Este", distance: 45.95 },
  { name: "Falcade", distance: 81.76 },
  { name: "Fara Vicentino", distance: 26.89 },
  { name: "Farra d'Alpago", distance: 68.48 },
  { name: "Farra di Soligo", distance: 36.35 },
  { name: "Feltre", distance: 44.47 },
  { name: "Ferrara di Monte Baldo", distance: 76.88 },
  { name: "Ficarolo", distance: 80.47 },
  { name: "Fiesso d'Artico", distance: 26.74 },
  { name: "Fiesso Umbertiano", distance: 75.24 },
  { name: "Follina", distance: 42.76 },
  { name: "Fontanelle", distance: 53.8 },
  { name: "Fontaniva", distance: 7.76 },
  { name: "Fonte", distance: 18.58 },
  { name: "Fonzaso", distance: 44.55 },
  { name: "Forno di Zoldo", distance: 85.23 },
  { name: "Fossalta di Piave", distance: 51.79 },
  { name: "Fossalta di Portogruaro", distance: 84.68 },
  { name: "Fossò", distance: 30.33 },
  { name: "Foza", distance: 35.18 },
  { name: "Frassinelle Polesine", distance: 70.19 },
  { name: "Fratta Polesine", distance: 67.28 },
  { name: "Fregona", distance: 57.51 },
  { name: "Fumane", distance: 75.3 },
  { name: "Gaiarine", distance: 57.12 },
  { name: "Gaiba", distance: 79.96 },
  { name: "Galliera Veneta", distance: 5.19 },
  { name: "Gallio", distance: 38.41 },
  { name: "Galzignano Terme", distance: 35.76 },
  { name: "Gambellara", distance: 43.11 },
  { name: "Gambugliano", distance: 31.84 },
  { name: "Garda", distance: 88.76 },
  { name: "Gavello", distance: 66.5 },
  { name: "Gazzo", distance: 11.76 },
  { name: "Gazzo Veronese", distance: 80.17 },
  { name: "Giacciano con Baruchella", distance: 68.58 },
  { name: "Giavera del Montello", distance: 31.8 },
  { name: "Godega di Sant'Urbano", distance: 55.13 },
  { name: "Gorgo al Monticano", distance: 57.95 },
  { name: "Gosaldo", distance: 67.62 },
  { name: "Grancona", distance: 37.61 },
  { name: "Grantorto", distance: 9.07 },
  { name: "Granze", distance: 52.3 },
  { name: "Grezzana", distance: 65.51 },
  { name: "Grisignano di Zocco", distance: 19.59 },
  { name: "Gruaro", distance: 81.14 },
  { name: "Grumolo delle Abbadesse", distance: 18.23 },
  { name: "Guarda Veneta", distance: 70.94 },
  { name: "Illasi", distance: 54.31 },
  { name: "Isola della Scala", distance: 75.81 },
  { name: "Isola Rizza", distance: 62.09 },
  { name: "Isola Vicentina", distance: 31.37 },
  { name: "Istrana", distance: 21.06 },
  { name: "Jesolo", distance: 62.36 },
  { name: "La Valle Agordina", distance: 75.61 },
  { name: "Laghi", distance: 50.15 },
  { name: "Lamon", distance: 48.28 },
  { name: "Lastebasse", distance: 55.3 },
  { name: "Lavagno", distance: 58.9 },
  { name: "Lazise", distance: 87.65 },
  { name: "Legnago", distance: 63.54 },
  { name: "Legnaro", distance: 32.11 },
  { name: "Lendinara", distance: 62.56 },
  { name: "Lentiai", distance: 49.27 },
  { name: "Limana", distance: 60.03 },
  { name: "Limena", distance: 16.17 },
  { name: "Livinallongo del Col di Lana", distance: 96.31 },
  { name: "Longare", distance: 24.19 },
  { name: "Longarone", distance: 80.11 },
  { name: "Lonigo", distance: 44.0 },
  { name: "Loreggia", distance: 8.18 },
  { name: "Lorenzago di Cadore", distance: 106.9 },
  { name: "Loreo", distance: 67.4 },
  { name: "Loria", distance: 12.57 },
  { name: "Lozzo Atestino", distance: 40.65 },
  { name: "Lozzo di Cadore", distance: 106.9 },
  { name: "Lugo di Vicenza", distance: 28.42 },
  { name: "Lusia", distance: 59.43 },
  { name: "Lusiana", distance: 28.06 },
  { name: "Malcesine", distance: 81.99 },
  { name: "Malo", distance: 34.39 },
  { name: "Mansuè", distance: 58.1 },
  { name: "Marano di Valpolicella", distance: 72.81 },
  { name: "Marano Vicentino", distance: 33.57 },
  { name: "Marcon", distance: 35.69 },
  { name: "Mareno di Piave", distance: 46.26 },
  { name: "Marostica", distance: 20.41 },
  { name: "Martellago", distance: 25.7 },
  { name: "Maser", distance: 23.36 },
  { name: "Maserà di Padova", distance: 33.22 },
  { name: "Maserada sul Piave", distance: 39.55 },
  { name: "Masi", distance: 63.07 },
  { name: "Mason Vicentino", distance: 21.69 },
  { name: "Massanzago", distance: 14.31 },
  { name: "Meduna di Livenza", distance: 63.2 },
  { name: "Megliadino San Fidenzio", distance: 51.42 },
  { name: "Megliadino San Vitale", distance: 53.07 },
  { name: "Mel", distance: 52.98 },
  { name: "Melara", distance: 79.81 },
  { name: "Meolo", distance: 47.11 },
  { name: "Merlara", distance: 59.3 },
  { name: "Mestrino", distance: 20.76 },
  { name: "Mezzane di Sotto", distance: 57.92 },
  { name: "Miane", distance: 41.17 },
  { name: "Minerbe", distance: 57.82 },
  { name: "Mira", distance: 30.01 },
  { name: "Mirano", distance: 24.75 },
  { name: "Mogliano Veneto", distance: 30.98 },
  { name: "Molvena", distance: 22.85 },
  { name: "Monastier di Treviso", distance: 45.9 },
  { name: "Monfumo", distance: 24.29 },
  { name: "Monselice", distance: 42.83 },
  { name: "Montagnana", distance: 52.07 },
  { name: "Monte di Malo", distance: 37.97 },
  { name: "Montebello Vicentino", distance: 40.22 },
  { name: "Montebelluna", distance: 23.5 },
  { name: "Montecchia di Crosara", distance: 48.37 },
  { name: "Montecchio Maggiore", distance: 36.6 },
  { name: "Montecchio Precalcino", distance: 22.57 },
  { name: "Monteforte d'Alpone", distance: 49.13 },
  { name: "Montegalda", distance: 23.27 },
  { name: "Montegaldella", distance: 24.38 },
  { name: "Montegrotto Terme", distance: 32.28 },
  { name: "Monteviale", distance: 30.84 },
  { name: "Monticello Conte Otto", distance: 20.56 },
  { name: "Montorso Vicentino", distance: 40.35 },
  { name: "Morgano", distance: 20.21 },
  { name: "Moriago della Battaglia", distance: 33.33 },
  { name: "Mossano", distance: 31.71 },
  { name: "Motta di Livenza", distance: 61.75 },
  { name: "Mozzecane", distance: 87.2 },
  { name: "Musile di Piave", distance: 55.86 },
  { name: "Mussolente", distance: 18.21 },
  { name: "Nanto", distance: 29.29 },
  { name: "Negrar", distance: 71.39 },
  { name: "Nervesa della Battaglia", distance: 35.97 },
  { name: "Noale", distance: 19.11 },
  { name: "Nogara", distance: 78.44 },
  { name: "Nogarole Rocca", distance: 83.32 },
  { name: "Nogarole Vicentino", distance: 43.82 },
  { name: "Nove", distance: 17.47 },
  { name: "Noventa di Piave", distance: 53.68 },
  { name: "Noventa Padovana", distance: 24.06 },
  { name: "Noventa Vicentina", distance: 43.64 },
  { name: "Occhiobello", distance: 80.24 },
  { name: "Oderzo", distance: 53.39 },
  { name: "Oppeano", distance: 62.54 },
  { name: "Orgiano", distance: 42.3 },
  { name: "Ormelle", distance: 48.23 },
  { name: "Orsago", distance: 56.6 },
  { name: "Ospedaletto Euganeo", distance: 47.67 },
  { name: "Ospitale di Cadore", distance: 87.07 },
  { name: "Paderno del Grappa", distance: 23.44 },
  { name: "Padova", distance: 23.38 },
  { name: "Paese", distance: 24.94 },
  { name: "Palù", distance: 62.88 },
  { name: "Papozze", distance: 71.76 },
  { name: "Pastrengo", distance: 82.6 },
  { name: "Pedavena", distance: 46.87 },
  { name: "Pedemonte", distance: 52.84 },
  { name: "Pederobba", distance: 30.02 },
  { name: "Perarolo di Cadore", distance: 95.04 },
  { name: "Pernumia", distance: 40.32 },
  { name: "Pescantina", distance: 77.74 },
  { name: "Peschiera del Garda", distance: 92.13 },
  { name: "Pettorazza Grimani", distance: 54.68 },
  { name: "Piacenza d'Adige", distance: 59.11 },
  { name: "Pianezze", distance: 21.75 },
  { name: "Pianiga", distance: 23.08 },
  { name: "Piazzola sul Brenta", distance: 9.75 },
  { name: "Pieve d'Alpago", distance: 72.54 },
  { name: "Pieve di Cadore", distance: 98.82 },
  { name: "Pieve di Soligo", distance: 40.16 },
  { name: "Pincara", distance: 72.07 },
  { name: "Piombino Dese", distance: 11.84 },
  { name: "Piove di Sacco", distance: 38.75 },
  { name: "Piovene Rocchette", distance: 35.5 },
  { name: "Poiana Maggiore", distance: 45.18 },
  { name: "Polesella", distance: 73.23 },
  { name: "Polverara", distance: 35.36 },
  { name: "Ponso", distance: 51.54 },
  { name: "Ponte di Piave", distance: 49.17 },
  { name: "Ponte nelle Alpi", distance: 71.12 },
  { name: "Ponte San Nicolò", distance: 29.18 },
  { name: "Pontecchio Polesine", distance: 66.54 },
  { name: "Pontelongo", distance: 43.51 },
  { name: "Ponzano Veneto", distance: 29.68 },
  { name: "Porto Tolle", distance: 83.12 },
  { name: "Porto Viro", distance: 72.19 },
  { name: "Portobuffolè", distance: 59.77 },
  { name: "Portogruaro", distance: 78.91 },
  { name: "Posina", distance: 49.23 },
  { name: "Possagno", distance: 26.18 },
  { name: "Pove del Grappa", distance: 21.99 },
  { name: "Povegliano", distance: 31.93 },
  { name: "Povegliano Veronese", distance: 80.9 },
  { name: "Pozzoleone", distance: 13.45 },
  { name: "Pozzonovo", distance: 47.04 },
  { name: "Pramaggiore", distance: 72.5 },
  { name: "Preganziol", distance: 30.27 },
  { name: "Pressana", distance: 50.6 },
  { name: "Puos d'Alpago", distance: 69.4 },
  { name: "Quarto d'Altino", distance: 41.17 },
  { name: "Quero", distance: 34.35 },
  { name: "Quinto di Treviso", distance: 25.1 },
  { name: "Quinto Vicentino", distance: 17.84 },
  { name: "Recoaro Terme", distance: 49.22 },
  { name: "Refrontolo", distance: 44.2 },
  { name: "Resana", distance: 8.61 },
  { name: "Revine Lago", distance: 50.93 },
  { name: "Riese Pio X", distance: 13.62 },
  { name: "Rivamonte Agordino", distance: 71.94 },
  { name: "Rivoli Veronese", distance: 80.69 },
  { name: "Roana", distance: 41.28 },
  { name: "Rocca Pietore", distance: 91.31 },
  { name: "Romano d'Ezzelino", distance: 20.9 },
  { name: "Roncà", distance: 46.12 },
  { name: "Roncade", distance: 41.07 },
  { name: "Ronco all'Adige", distance: 56.44 },
  { name: "Rosà", distance: 13.74 },
  { name: "Rosolina", distance: 67.84 },
  { name: "Rossano Veneto", distance: 10.26 },
  { name: "Rotzo", distance: 44.19 },
  { name: "Roverchiara", distance: 61.0 },
  { name: "Roverè Veronese", distance: 60.54 },
  { name: "Roveredo di Guà", distance: 49.49 },
  { name: "Rovigo", distance: 61.1 },
  { name: "Rovolon", distance: 31.63 },
  { name: "Rubano", distance: 22.09 },
  { name: "Saccolongo", distance: 25.13 },
  { name: "Salara", distance: 77.81 },
  { name: "Salcedo", distance: 26.6 },
  { name: "Saletto", distance: 50.08 },
  { name: "Salgareda", distance: 51.05 },
  { name: "Salizzole", distance: 72.47 },
  { name: "Salzano", distance: 22.9 },
  { name: "San Bellino", distance: 68.37 },
  { name: "San Biagio di Callalta", distance: 41.89 },
  { name: "San Bonifacio", distance: 51.29 },
  { name: "San Donà di Piave", distance: 55.97 },
  { name: "San Fior", distance: 51.94 },
  { name: "San Germano dei Berici", distance: 37.94 },
  { name: "San Giorgio delle Pertiche", distance: 9.93 },
  { name: "San Giorgio in Bosco", distance: 4.42 },
  { name: "San Giovanni Ilarione", distance: 48.65 },
  { name: "San Giovanni Lupatoto", distance: 67.92 },
  { name: "San Gregorio nelle Alpi", distance: 55.87 },
  { name: "San Martino Buon Albergo", distance: 62.63 },
  { name: "San Martino di Lupari", distance: 3.6 },
  { name: "San Martino di Venezze", distance: 54.39 },
  { name: "San Mauro di Saline", distance: 57.41 },
  { name: "San Michele al Tagliamento", distance: 90.63 },
  { name: "San Nazario", distance: 27.47 },
  { name: "San Nicolò di Comelico", distance: 119.3 },
  { name: "San Pietro di Cadore", distance: 121.07 },
  { name: "San Pietro di Feletto", distance: 45.57 },
  { name: "San Pietro di Morubio", distance: 63.81 },
  { name: "San Pietro in Cariano", distance: 75.72 },
  { name: "San Pietro in Gu", distance: 13.57 },
  { name: "San Pietro Mussolino", distance: 45.81 },
  { name: "San Pietro Viminario", distance: 41.69 },
  { name: "San Polo di Piave", distance: 46.71 },
  { name: "San Tomaso Agordino", distance: 85.42 },
  { name: "San Vendemiano", distance: 49.22 },
  { name: "San Vito di Cadore", distance: 97.75 },
  { name: "San Vito di Leguzzano", distance: 37.59 },
  { name: "San Zeno di Montagna", distance: 86.61 },
  { name: "San Zenone degli Ezzelini", distance: 18.1 },
  { name: "Sandrigo", distance: 19.51 },
  { name: "Sanguinetto", distance: 72.68 },
  { name: "Sant'Ambrogio di Valpolicella", distance: 79.31 },
  { name: "Sant'Angelo di Piove di Sacco", distance: 32.5 },
  { name: "Sant'Anna d'Alfaedo", distance: 69.63 },
  { name: "Sant'Elena", distance: 49.11 },
  { name: "Sant'Urbano", distance: 56.72 },
  { name: "Santa Giustina", distance: 53.87 },
  { name: "Santa Giustina in Colle", distance: 7.73 },
  { name: "Santa Lucia di Piave", distance: 42.05 },
  { name: "Santa Margherita d'Adige", distance: 50.49 },
  { name: "Santa Maria di Sala", distance: 19.4 },
  { name: "Santo Stefano di Cadore", distance: 117.8 },
  { name: "Santo Stino di Livenza", distance: 66.22 },
  { name: "Santorso", distance: 37.61 },
  { name: "Saonara", distance: 30.1 },
  { name: "Sappada", distance: 123.73 },
  { name: "Sarcedo", distance: 26.3 },
  { name: "Sarego", distance: 41.67 },
  { name: "Sarmede", distance: 57.76 },
  { name: "Schiavon", distance: 17.88 },
  { name: "Schio", distance: 39.38 },
  { name: "Scorzè", distance: 20.99 },
  { name: "Sedico", distance: 58.09 },
  { name: "Segusino", distance: 34.35 },
  { name: "Selva di Cadore", distance: 93.72 },
  { name: "Selva di Progno", distance: 55.05 },
  { name: "Selvazzano Dentro", distance: 25.89 },
  { name: "Seren del Grappa", distance: 41.15 },
  { name: "Sernaglia della Battaglia", distance: 36.1 },
  { name: "Silea", distance: 35.22 },
  { name: "Soave", distance: 51.55 },
  { name: "Solagna", distance: 24.58 },
  { name: "Solesino", distance: 49.59 },
  { name: "Sommacampagna", distance: 81.81 },
  { name: "Sona", distance: 81.64 },
  { name: "Sorgà", distance: 81.18 },
  { name: "Sospirolo", distance: 60.71 },
  { name: "Sossano", distance: 38.68 },
  { name: "Soverzene", distance: 74.13 },
  { name: "Sovizzo", distance: 32.71 },
  { name: "Sovramonte", distance: 49.23 },
  { name: "Spinea", distance: 28.81 },
  { name: "Spresiano", distance: 36.47 },
  { name: "Stanghella", distance: 54.21 },
  { name: "Stienta", distance: 78.91 },
  { name: "Stra", distance: 27.04 },
  { name: "Susegana", distance: 40.69 },
  { name: "Taglio di Po", distance: 73.74 },
  { name: "Taibon Agordino", distance: 77.03 },
  { name: "Tambre", distance: 71.91 },
  { name: "Tarzo", distance: 49.51 },
  { name: "Teglio Veneto", distance: 83.49 },
  { name: "Teolo", distance: 32.98 },
  { name: "Terrassa Padovana", distance: 41.8 },
  { name: "Terrazzo", distance: 60.75 },
  { name: "Tezze sul Brenta", distance: 13.31 },
  { name: "Thiene", distance: 30.2 },
  { name: "Tombolo", distance: 3.33 },
  { name: "Tonezza del Cimone", distance: 46.87 },
  { name: "Torre di Mosto", distance: 67.04 },
  { name: "Torrebelvicino", distance: 42.34 },
  { name: "Torreglia", distance: 32.75 },
  { name: "Torri del Benaco", distance: 90.22 },
  { name: "Torri di Quartesolo", distance: 21.3 },
  { name: "Trebaseleghe", distance: 16.16 },
  { name: "Trecenta", distance: 71.87 },
  { name: "Tregnago", distance: 54.35 },
  { name: "Trevenzuolo", distance: 80.97 },
  { name: "Trevignano", distance: 23.6 },
  { name: "Treviso", distance: 31.18 },
  { name: "Tribano", distance: 45.6 },
  { name: "Trichiana", distance: 55.28 },
  { name: "Trissino", distance: 37.41 },
  { name: "Urbana", distance: 56.68 },
  { name: "Valdagno", distance: 42.59 },
  { name: "Valdastico", distance: 48.01 },
  { name: "Valdobbiadene", distance: 33.47 },
  { name: "Valeggio sul Mincio", distance: 91.42 },
  { name: "Vallada Agordina", distance: 83.06 },
  { name: "Valle di Cadore", distance: 96.65 },
  { name: "Valli del Pasubio", distance: 47.38 },
  { name: "Valstagna", distance: 29.94 },
  { name: "Vas", distance: 36.29 },
  { name: "Vazzola", distance: 48.59 },
  { name: "Vedelago", distance: 15.29 },
  { name: "Veggiano", distance: 21.61 },
  { name: "Velo d'Astico", distance: 41.89 },
  { name: "Velo Veronese", distance: 58.39 },
  { name: "Venezia", distance: 43.47 },
  { name: "Verona", distance: 69.16 },
  { name: "Veronella", distance: 52.33 },
  { name: "Vescovana", distance: 54.69 },
  { name: "Vestenanova", distance: 48.28 },
  { name: "Vicenza", distance: 25.19 },
  { name: "Vidor", distance: 30.83 },
  { name: "Vigasio", distance: 78.19 },
  { name: "Vighizzolo d'Este", distance: 52.02 },
  { name: "Vigo di Cadore", distance: 109.21 },
  { name: "Vigodarzere", distance: 17.78 },
  { name: "Vigonovo", distance: 28.37 },
  { name: "Vigonza", distance: 22.83 },
  { name: "Villa Bartolomea", distance: 64.1 },
  { name: "Villa del Conte", distance: 4.06 },
  { name: "Villa Estense", distance: 51.55 },
  { name: "Villadose", distance: 61.15 },
  { name: "Villafranca di Verona", distance: 83.71 },
  { name: "Villafranca Padovana", distance: 14.58 },
  { name: "Villaga", distance: 34.21 },
  { name: "Villamarzana", distance: 68.18 },
  { name: "Villanova del Ghebbo", distance: 64.18 },
  { name: "Villanova di Camposampiero", distance: 17.2 },
  { name: "Villanova Marchesana", distance: 70.17 },
  { name: "Villaverla", distance: 28.11 },
  { name: "Villorba", distance: 33.81 },
  { name: "Vittorio Veneto", distance: 53.52 },
  { name: "Vo'", distance: 35.92 },
  { name: "Vodo Cadore", distance: 94.16 },
  { name: "Volpago del Montello", distance: 27.39 },
  { name: "Voltago Agordino", distance: 73.78 },
  { name: "Zanè", distance: 32.43 },
  { name: "Zenson di Piave", distance: 50.4 },
  { name: "Zermeghedo", distance: 40.34 },
  { name: "Zero Branco", distance: 24.91 },
  { name: "Zevio", distance: 61.56 },
  { name: "Zimella", distance: 48.55 },
  { name: "Zoldo Alto", distance: 86.89 },
  { name: "Zoppè di Cadore", distance: 89.15 },
  { name: "Zovencedo", distance: 33.98 },
  { name: "Zugliano", distance: 27.93 },
];
